project_id = "bqxaiibbcpbhacwkqxkr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.get-estimate]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-webhook-estimates]
verify_jwt = false

[functions.estimate-checkout]
verify_jwt = false

[functions.create-stripe-customer]
verify_jwt = false

[functions.check-trial-expiration]
verify_jwt = false

[functions.backfill-stripe-customers]
verify_jwt = true